version: "3"

services:
  bootdemo :
    build: .
    #https://panditasagar01:SUnshine@143@github.com/panditasagar01/spring-boot-example.git
    image: boot-image
    container_name: boot_App
    environment:
     - server_port=8087
    ports:
      - "9090:8087"

# Below command will shut down, pull latest image and run it
# docker-compose down && docker-compose pull && docker-compose up -d